---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: nlp-sd-dataset
  labels:
    type: local
spec:
  storageClassName: nlp-sd-dataset
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/workspace/www/NLP_smart_dispatching/datasets"
