---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: nlp-sd-output
  labels:
    type: local
spec:
  storageClassName: nlp-sd-output
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/workspace/www/NLP_smart_dispatching/output"
