---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nlp-sd-dataset
spec:
  storageClassName: nlp-sd-dataset
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
